cask_args appdir: '/Applications'

tap 'homebrew/bundle'
tap 'caskroom/versions'

brew 'coreutils'
brew 'git'
brew 'git-lfs'
brew 'java8'
brew 'jenv'
brew 'jq'
brew 'maven'
brew 'openssl'
brew 'ssh-copy-id'
brew 'terraform'
brew 'tig'
brew 'unrar'
brew 'wget'

cask 'commander-one'
cask 'docker'
cask 'dropbox'
cask 'google-backup-and-sync'
cask 'google-chrome'
cask 'intellij-idea'
cask 'iterm2'
cask 'microsoft-office'
cask 'microsoft-teams'
cask 'postman'
cask 'skype-preview'
cask 'skype-for-business'
cask 'slack'
cask 'slate'
cask 'ultimaker-cura'
cask 'vagrant'
cask 'virtualbox'
cask 'visual-studio-code'
cask 'vlc'
cask 'wireshark'
